services:
  app:
    build:
      context: .
    working_dir: /app
    tty: true
    stdin_open: true
    ports:
      - "5175:5175" # React Router dev server
      - "4175:4175" # vite preview server
    volumes:
      - ./:/app
      - ~/.bashrc:/root/.bashrc
      - ./.devcontainer/.vimrc:/root/.vimrc
      - node_modules:/app/node_modules
  prism:
    image: stoplight/prism:5
    ports:
      - "5177:4010"
    command: mock -h 0.0.0.0 /openapi/openapi.yml
    volumes:
      - ./openapi:/openapi
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./openapi/openapi.yaml:/usr/share/nginx/html/openapi.yml
    environment:
      API_URL: openapi.yml
    ports:
      - "8080:8080"
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./packages/backend/db/mysql_data:/var/lib/mysql
    command: mysqld --innodb_use_native_aio=0

volumes:
  node_modules:
