/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { Hono } from "hono";

import { createPetsHandlers } from "./controllers/createPets";
import { listPetsHandlers } from "./controllers/listPets";
import { showPetByIdHandlers } from "./controllers/showPetById";

const app = new Hono();

/**
 * @summary List all pets
 */

app.get("/pets", ...listPetsHandlers);

/**
 * @summary Create a pet
 */

app.post("/pets", ...createPetsHandlers);

/**
 * @summary Info for a specific pet
 */

app.get("/pets/:petId", ...showPetByIdHandlers);

export default app;
